version: "3"

tasks:
  run:
    desc: Run dev server
    cmds:
      - go run ./cmd/server

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  build:
    desc: Build binary
    cmds:
      - go build -o bin/server ./cmd/server

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  tidy:
    desc: Tidy dependencies and download modules
    cmds:
      - go mod tidy
      - go mod download

  docker:build:
    desc: Build docker image
    cmds:
      - docker build -t pack-calculator .

  docker:run:
    desc: Run docker container
    deps:
      - docker:build
    cmds:
      - docker run --rm -p 8080:8080 pack-calculator
